### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by SanketDG** [codingforentrepreneurs/Try-Django-1.8#1]
I was browsing through the code first before watching the videos. I wanted to grab a quick demo of the final product, and cloned this repo, but I got confused on which libraries to install.

A requirements.txt file with all the dependencies and their versions could be helpful.

**Comment by codingforentrepreneurs** [comment]
It exists in "src"

https://github.com/codingforentrepreneurs/Try-Django-1.8/blob/master/src/requirements.txt

Cheers!

**Comment by SanketDG** [comment]
Somehow I thought it should have been in the top level folder. But it makes more sense to have it in `src`. Thanks!

**Comment by codingforentrepreneurs** [comment]
Anytime.
